# Generated by Django 4.2.4 on 2023-11-03 04:13

from django.db import migrations


def migrate_person_ges(apps, scheme_editor):
    person_ages = apps.get_model("main_app", "Person")

    for ages in person_ages.objects.all():
        if ages.age <= 12:
            ages.age_group = "Child"
        elif ages.age <= 17:
            ages.age_group = "Teen"
        else:
            ages.age_group = "Adult"
        ages.save()


def delete_person_ages(apps, scheme_editor):
    person_ages = apps.get_model("main_app", "Person")

    for ages in person_ages.objects.all():
        ages.age_group = "No age group"
        ages.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(migrate_person_ges, reverse_code=delete_person_ages)
    ]
